# Generated by Django 2.2 on 2019-10-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_cleaning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='tittle',
            new_name='title',
        ),
    ]
